baseURL = "/"
title = "BEATLEMEDIA"
languageCode = "en"
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "hugo.386"
preserveTaxonomyNames = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "BEATLEMEDIA"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "Picture yourself in a boat on a river" 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "ANOTHER blog about those guys? You're kidding right?"

    # The name to display in the copyright section in the footer
    copyrightname = "MD Roberts"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = "http://retrofuture.netlify.app"

    # Show the "built on Hugo" disclaimer
    showhugo = false

    # Urls for social networks
    facebook = "https://facebook.com/mr05301"
    twitter = "https://twitter.com/dokoissho"
    github = "https://github.com/mroberts1"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 4

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = true

[params.copyright]
    name = "MD Roberts"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = "http://retrofuture.netlify.app"

    # Text to go before copyright information
    prefix = "2021"

    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = "BEATLEMEDIA"

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "posts"
    name = "All posts"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.twitter]
    disableInlineCSS = true